//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.05 at 01:20:06 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tech.vision.com/soap/employees", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vision.tech.soap.employees;
